spring:
  application:
    name: PrestoTest

  datasource:
    # PrestoDB 서버 주소 및 기본 카탈로그 설정
    url: jdbc:presto://localhost:8080/mysql/default
    driver-class-name: com.facebook.presto.jdbc.PrestoDriver
    username: ms
